# Generated by Django 4.2.1 on 2023-06-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuran_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugurta',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='description_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='description_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sugurta',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
