# Generated by Django 4.2.1 on 2023-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuran_app', '0002_sugurta_description_en_sugurta_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugurta',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
